[package]
name = "traits"
version = "0.1.0"
authors = ["Matthew Miller <mxmdmiller@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "traits"
path = "src/lib.rs"

[dependencies]
